// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(CondosmartContext))]
    partial class CondosmartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.AreaDeLazer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<bool?>("Disponibilidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponibilidade")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CondominioId" }, "fk_area_condominio");

                    b.HasIndex(new[] { "SindicoId" }, "fk_area_sindico");

                    b.ToTable("area_de_lazer", (string)null);
                });

            modelBuilder.Entity("Core.Models.Ata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<string>("Conteudo")
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DataReuniao")
                        .HasColumnType("date")
                        .HasColumnName("data_reuniao");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Temas")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("temas");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CondominioId" }, "fk_atas_condominio");

                    b.HasIndex(new[] { "SindicoId" }, "fk_atas_sindico");

                    b.ToTable("atas", (string)null);
                });

            modelBuilder.Entity("Core.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataChamado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_chamado")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<int?>("MoradorId")
                        .HasColumnType("int")
                        .HasColumnName("morador_id");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('aberto','em_andamento','resolvido','cancelado')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'aberto'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CondominioId" }, "fk_chamado_condominio");

                    b.HasIndex(new[] { "MoradorId" }, "fk_chamado_morador");

                    b.HasIndex(new[] { "SindicoId" }, "fk_chamado_sindico");

                    b.ToTable("chamados", (string)null);
                });

            modelBuilder.Entity("Core.Models.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("char(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<string>("Complemento")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("complemento");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("rua");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.Property<int?>("Unidades")
                        .HasColumnType("int")
                        .HasColumnName("unidades");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cnpj" }, "cnpj")
                        .IsUnique();

                    b.HasIndex(new[] { "SindicoId" }, "fk_condominio_sindico");

                    b.ToTable("condominios", (string)null);
                });

            modelBuilder.Entity("Core.Models.Morador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("bairro");

                    b.Property<byte[]>("Biometria")
                        .HasColumnType("blob")
                        .HasColumnName("biometria");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("complemento");

                    b.Property<int?>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rg")
                        .HasMaxLength(9)
                        .HasColumnType("char(9)")
                        .HasColumnName("rg")
                        .IsFixedLength();

                    b.Property<string>("Rua")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "cpf")
                        .IsUnique();

                    b.HasIndex(new[] { "CondominioId" }, "fk_morador_condominio");

                    b.ToTable("moradores", (string)null);
                });

            modelBuilder.Entity("Core.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("enum('pix','cartao_credito','cartao_debito','boleto','dinheiro')")
                        .HasColumnName("forma_pagamento");

                    b.Property<int?>("MoradorId")
                        .HasColumnType("int")
                        .HasColumnName("morador_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pendente','pago','cancelado','estornado')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pendente'");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int")
                        .HasColumnName("unidade_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CondominioId" }, "ix_pagamentos_condominio");

                    b.HasIndex(new[] { "MoradorId" }, "ix_pagamentos_morador");

                    b.HasIndex(new[] { "UnidadeId" }, "ix_pagamentos_unidade");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("Core.Models.Porteiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("rua");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "cpf")
                        .IsUnique()
                        .HasDatabaseName("cpf1");

                    b.HasIndex(new[] { "SindicoId" }, "fk_porteiro_sindico");

                    b.ToTable("porteiros", (string)null);
                });

            modelBuilder.Entity("Core.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<int>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("data_inicio");

                    b.Property<int?>("MoradorId")
                        .HasColumnType("int")
                        .HasColumnName("morador_id");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('confirmado','pendente','cancelado','concluido')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'confirmado'");

                    b.Property<int?>("VisitanteId")
                        .HasColumnType("int")
                        .HasColumnName("visitante_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AreaId" }, "fk_reserva_area");

                    b.HasIndex(new[] { "CondominioId" }, "fk_reserva_condominio");

                    b.HasIndex(new[] { "MoradorId" }, "fk_reserva_morador");

                    b.HasIndex(new[] { "SindicoId" }, "fk_reserva_sindico");

                    b.HasIndex(new[] { "VisitanteId" }, "fk_reserva_visitante");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("Core.Models.Sindico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "cpf")
                        .IsUnique()
                        .HasDatabaseName("cpf2");

                    b.ToTable("sindicos", (string)null);
                });

            modelBuilder.Entity("Core.Models.UnidadesResidenciais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("complemento");

                    b.Property<int>("CondominioId")
                        .HasColumnType("int")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("FotoRosto")
                        .HasColumnType("blob")
                        .HasColumnName("foto_rosto");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("identificador");

                    b.Property<int?>("MoradorId")
                        .HasColumnType("int")
                        .HasColumnName("morador_id");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("rua");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("TelefoneCelular")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone_celular")
                        .IsFixedLength();

                    b.Property<string>("TelefoneResidencial")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone_residencial")
                        .IsFixedLength();

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MoradorId" }, "fk_unidade_morador");

                    b.HasIndex(new[] { "SindicoId" }, "fk_unidade_sindico");

                    b.HasIndex(new[] { "CondominioId", "Identificador" }, "ux_unidade_ident_condominio")
                        .IsUnique();

                    b.ToTable("unidades_residenciais", (string)null);
                });

            modelBuilder.Entity("Core.Models.Visitantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataHoraEntrada")
                        .HasColumnType("datetime")
                        .HasColumnName("data_hora_entrada");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("datetime")
                        .HasColumnName("data_hora_saida");

                    b.Property<int?>("MoradorId")
                        .HasColumnType("int")
                        .HasColumnName("morador_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observacao");

                    b.Property<int?>("PorteiroId")
                        .HasColumnType("int")
                        .HasColumnName("porteiro_id");

                    b.Property<int?>("SindicoId")
                        .HasColumnType("int")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MoradorId" }, "fk_visitante_morador");

                    b.HasIndex(new[] { "PorteiroId" }, "fk_visitante_porteiro");

                    b.HasIndex(new[] { "SindicoId" }, "fk_visitante_sindico");

                    b.HasIndex(new[] { "UnidadeId" }, "fk_visitante_unidade");

                    b.ToTable("visitantes", (string)null);
                });

            modelBuilder.Entity("Core.Models.AreaDeLazer", b =>
                {
                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("AreaDeLazers")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_area_condominio");

                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("AreaDeLazers")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_area_sindico");

                    b.Navigation("Condominio");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("Core.Models.Ata", b =>
                {
                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("Ata")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_atas_condominio");

                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("Ata")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_atas_sindico");

                    b.Navigation("Condominio");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("Core.Models.Chamado", b =>
                {
                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("Chamados")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chamado_condominio");

                    b.HasOne("Core.Models.Morador", "Morador")
                        .WithMany("Chamados")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chamado_morador");

                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("Chamados")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chamado_sindico");

                    b.Navigation("Condominio");

                    b.Navigation("Morador");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("Core.Models.Condominio", b =>
                {
                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("Condominios")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_condominio_sindico");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("Core.Models.Morador", b =>
                {
                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("Moradores")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_morador_condominio");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Core.Models.Pagamento", b =>
                {
                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("Pagamentos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagamento_condominio");

                    b.HasOne("Core.Models.Morador", "Morador")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pagamento_morador");

                    b.HasOne("Core.Models.UnidadesResidenciais", "Unidade")
                        .WithMany("Pagamentos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pagamento_unidade");

                    b.Navigation("Condominio");

                    b.Navigation("Morador");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Core.Models.Porteiro", b =>
                {
                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("Porteiros")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_porteiro_sindico");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("Core.Models.Reserva", b =>
                {
                    b.HasOne("Core.Models.AreaDeLazer", "Area")
                        .WithMany("Reservas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_area");

                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("Reservas")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_condominio");

                    b.HasOne("Core.Models.Morador", "Morador")
                        .WithMany("Reservas")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reserva_morador");

                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("Reservas")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reserva_sindico");

                    b.HasOne("Core.Models.Visitantes", "Visitante")
                        .WithMany("Reservas")
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reserva_visitante");

                    b.Navigation("Area");

                    b.Navigation("Condominio");

                    b.Navigation("Morador");

                    b.Navigation("Sindico");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Core.Models.UnidadesResidenciais", b =>
                {
                    b.HasOne("Core.Models.Condominio", "Condominio")
                        .WithMany("UnidadesResidenciais")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unidade_condominio");

                    b.HasOne("Core.Models.Morador", "Morador")
                        .WithMany("UnidadesResidenciais")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_unidade_morador");

                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("UnidadesResidenciais")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_unidade_sindico");

                    b.Navigation("Condominio");

                    b.Navigation("Morador");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("Core.Models.Visitantes", b =>
                {
                    b.HasOne("Core.Models.Morador", "Morador")
                        .WithMany("Visitantes")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_visitante_morador");

                    b.HasOne("Core.Models.Porteiro", "Porteiro")
                        .WithMany("Visitantes")
                        .HasForeignKey("PorteiroId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_visitante_porteiro");

                    b.HasOne("Core.Models.Sindico", "Sindico")
                        .WithMany("Visitantes")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_visitante_sindico");

                    b.HasOne("Core.Models.UnidadesResidenciais", "Unidade")
                        .WithMany("Visitantes")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_visitante_unidade");

                    b.Navigation("Morador");

                    b.Navigation("Porteiro");

                    b.Navigation("Sindico");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Core.Models.AreaDeLazer", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Core.Models.Condominio", b =>
                {
                    b.Navigation("AreaDeLazers");

                    b.Navigation("Ata");

                    b.Navigation("Chamados");

                    b.Navigation("Moradores");

                    b.Navigation("Pagamentos");

                    b.Navigation("Reservas");

                    b.Navigation("UnidadesResidenciais");
                });

            modelBuilder.Entity("Core.Models.Morador", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Pagamentos");

                    b.Navigation("Reservas");

                    b.Navigation("UnidadesResidenciais");

                    b.Navigation("Visitantes");
                });

            modelBuilder.Entity("Core.Models.Porteiro", b =>
                {
                    b.Navigation("Visitantes");
                });

            modelBuilder.Entity("Core.Models.Sindico", b =>
                {
                    b.Navigation("AreaDeLazers");

                    b.Navigation("Ata");

                    b.Navigation("Chamados");

                    b.Navigation("Condominios");

                    b.Navigation("Porteiros");

                    b.Navigation("Reservas");

                    b.Navigation("UnidadesResidenciais");

                    b.Navigation("Visitantes");
                });

            modelBuilder.Entity("Core.Models.UnidadesResidenciais", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("Visitantes");
                });

            modelBuilder.Entity("Core.Models.Visitantes", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
